id: PD3D0B311
initial_creation_type: input
source_metadata:
  title: Lamrim Series
  language: pt
  description: Texts on the subject of the graduated path (lam rim), which was introduced
    to Tibet by Atiśa in his most important work Lamp for the Path of Awakening (Bodhipathapradīpa)
    and subsequently adopted by all schools of Tibetan Buddhism, especially the Kadam
    and Gelug.
  volume:
    a08b91ac02e24c65812c5287cf3c03a8:
      title: The Lamp for the Path to Enlightenment
      parent: Advice
    7122ce7315dd43dfb57d9c0d92f16857:
      title: 'A Precious Garland for the Supreme Path of the Three Types of Individual:
        The Root of Dakpo''s Four Dharmas'
      parent: Advice
    309779d2168b46bda1d2049fa5d2138a:
      title: 'Sweet Nectar of the Supreme Vehicle: A Synopsis of the Stages of the
        Mahāyāna Path'
      parent: Advice
    e2fda592773940a9ac014a6b555bf620:
      title: 'The Essence of Nectar: Graduated Stages of the Path — Advice for Renunciant
        Meditators'
      parent: Advice
    aebc73a14a5a47b6ad83c97e5a05db9c:
      title: Three Principal Aspects of the Path
      parent: Advice
    e45eb31f328e4a0ab3b6c1fc3bc97ee9:
      title: A Brief Commentary on the Twelve Stanzas (Including the Divisions of
        the Stages of the Path for Individuals of the Three Capacities)
      parent: Commentaries
    8aebec67ea734499a61cbd2bf84bca1b:
      title: 'A Few Words of Commentary to Clarify The Essence of Nectar: Graduated
        Stages of the Path—Advice for Renunciant Meditators'
      parent: Commentaries
    cf5f1b5cf1c64712b2e35a57dd7f76fe:
      title: 'The Swift Infusion of Blessings: A Prayer and Aspiration for the Stages
        of the Path Combined with Guru Yoga'
      parent: Guru Yoga
    2883ec5dcf0c406fa3ea40059bb40d0a:
      title: Aspiration for the Stages of the Path
      parent: Prayers
    1b30b751cd6249abb9f0043e5c285d0a:
      title: The Foundation of All Qualities
      parent: Prayers
created_at: '2022-03-01T04:07:49.610779'
last_modified_at: '2022-03-01T04:07:49.610781'
